version: "3"
services:
  
  app:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 4
      start_period: 20s
      timeout: 10s
    env_file:
      - .env
    # command: >
    #   sh -c "pytest tests/"
    restart: unless-stopped

  redis:
    image: redis:7-alpine

  